version: "3.6"
services:

  openindoor-io-build:
    image: node:14
    working_dir: /code
    volumes:
    - .:/code/
    entrypoint: bash -c
    command:
    - |
      set -e
      set -x
      # yarn add file:./mapbox-gl-openindoor/dist/mapbox-gl-openindoor.cjs.js
      yarn install --frozen-lockfile
      yarn run build

  openindoor-io-run:
    image: nginx:alpine
    ports:
    - 8100:80
    volumes:
    - ./nginx_gzip.conf:/etc/nginx/conf.d/nginx_gzip.conf
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./dist/:/usr/share/nginx/html/
